import Head from "next/head";
import Image from "next/image";
import Body from "../components/Body";
import Companies from "../components/Companies";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Liner - The issue tracking tool you'll enjoy using</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Header />
        <Body />
        <Companies />
      </main>

      <footer></footer>
    </div>
  );
}
